import { createSlice } from "@reduxjs/toolkit";

export const Users = createSlice({
  name: "Users",
  initialState: {
    Users: [
      {
        ID: "dl-5234",
        age:'20',
        image:'https://th.bing.com/th/id/OIP.GlXqxcR9EmviN5kuwaUsMQHaIB?rs=1&pid=ImgDetMain',
        Name: "John Doe",
        fname: "John",
        lname: "Doe",
        email: "john.doe@gmail.com",
        phone: "+1(609)784-5678",
        About: "dsl,;fkasfklmerokfv, m ,fmgkmfvn jfdgldfgjlgarunvffjl",
        inProgress: ["1", "2", "3"],
        progress: ["4", "5", "6"],
        Nationality: "EGYPT",
        Country: "EGYPT",
        City: "Cairo",
        University: "international Islamic University",
        Major: "Computer Science",
        GraduationYear: "2020",
        password: "12345678",
        Role: "Admin",
        Status: "Active",
        Score: 0,
      },
      {
        ID: "dl-552314",
        age:'20',
        image:'https://th.bing.com/th/id/OIP.GlXqxcR9EmviN5kuwaUsMQHaIB?rs=1&pid=ImgDetMain',
        Name: "John no",
        fname: "John",
        lname: "no",
        email: "johndoe@gmail.com",
        phone: "+1(609)784-5678",
        About: "dsl,;fkasfklmerokfv, m ,fmgkmfvn jfdgldfgjlgarunvffjl",
        inProgress: ["1", "2", "3"],
        progress: ["4", "5", "6"],
        Nationality: "EGYPT",
        Country: "EGYPT",
        City: "Cairo",
        University: "international Islamic University",
        Major: "Computer Science",
        GraduationYear: "2020",
        password: "12345678",
        Role: "Student",
        EarnedCertificates: [
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            DateDay: "5th",
            DateMonth: "Jun",
            certificate:
              "/https://images.pexels.com/photos/268533/pexels-photo-268533.jpeg?cs=srgb&dl=pexels-pixabay-268533.jpg&fm=jpg",
              image:'https://th.bing.com/th/id/OIP.GlXqxcR9EmviN5kuwaUsMQHaIB?rs=1&pid=ImgDetMain',
            date: "12:30",
            category: "web",
            level: "1",
          },
        ],
        Status: "Active",
        Score: 0,
        upcomingExams: [
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            DateDay: "5th",
            DateMonth: "Jun",
            date: "12:30",
            category: "web",
            level: "1",
          },
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            DateDay: "5th",
            DateMonth: "Jun",
            date: "12:30",
            category: "web",
            level: "1",
          },
        ],
        RegisteredCourses: ["1", "2", "7"],
      },
      {
        ID: "dl-21231",
        age:'20',
        image:'https://th.bing.com/th/id/OIP.GlXqxcR9EmviN5kuwaUsMQHaIB?rs=1&pid=ImgDetMain',
        Name: "John Doe",
        fname: "John",
        lname: "Doe",
        email: "john.doe@gmail.com",
        phone: "+1(609)784-5678",
        About: "dsl,;fkasfklmerokfv, m ,fmgkmfvn jfdgldfgjlgarunvffjl",
        inProgress: ["1", "2", "3"],
        progress: ["4", "5", "6"],
        Nationality: "EGYPT",
        Country: "EGYPT",
        City: "Cairo",
        University: "international Islamic University",
        Major: "Computer Science",
        GraduationYear: "2020",
        password: "12345678",
        Role: "Admin",
        Status: "Active",
        Score: 0,
      },
      {
        ID: "dl-481",
        age:'20',
        image:'https://th.bing.com/th/id/OIP.GlXqxcR9EmviN5kuwaUsMQHaIB?rs=1&pid=ImgDetMain',
        Name: "John Doe",
        fname: "John",
        lname: "Doe",
        email: "john.doe@gmail.com",
        phone: "+1(609)784-5678",
        About: "dsl,;fkasfklmerokfv, m ,fmgkmfvn jfdgldfgjlgarunvffjl",
        inProgress: ["1", "2", "3"],
        progress: ["4", "5", "6"],
        Nationality: "EGYPT",
        Country: "EGYPT",
        City: "Cairo",
        University: "international Islamic University",
        Major: "Computer Science",
        GraduationYear: "2020",
        password: "12345678",
        Role: "Admin",
        Status: "Active",
        Score: 0,
      },
      {
        ID: "dl-121",
        age:'20',
        image:'https://th.bing.com/th/id/OIP.GlXqxcR9EmviN5kuwaUsMQHaIB?rs=1&pid=ImgDetMain',
        Name: "John Doe",
        fname: "John",
        lname: "Doe",
        email: "john.doe@gmail.com",
        phone: "+1(609)784-5678",
        About: "dsl,;fkasfklmerokfv, m ,fmgkmfvn jfdgldfgjlgarunvffjl",
        inProgress: ["1", "2", "3"],
        progress: ["4", "5", "6"],
        Nationality: "EGYPT",
        Country: "EGYPT",
        City: "Cairo",
        University: "international Islamic University",
        Major: "Computer Science",
        GraduationYear: "2020",
        password: "12345678",
        Role: "Admin",
        Status: "Active",
        Score: 0,
      },
      {
        ID: "dl-48231",
        age:'20',
        image:'https://th.bing.com/th/id/OIP.GlXqxcR9EmviN5kuwaUsMQHaIB?rs=1&pid=ImgDetMain',
        Name: "John Doe",
        fname: "John",
        lname: "Doe",
        email: "john.doe@gmail.com",
        phone: "+1(609)784-5678",
        About: "dsl,;fkasfklmerokfv, m ,fmgkmfvn jfdgldfgjlgarunvffjl",
        inProgress: ["1", "2", "3"],
        progress: ["4", "5", "6"],
        Nationality: "EGYPT",
        Country: "EGYPT",
        City: "Cairo",
        University: "international Islamic University",
        Major: "Computer Science",
        GraduationYear: "2020",
        password: "12345678",
        Role: "Admin",
        Status: "Active",
        Score: 0,
      },
      {
        ID: "dl-5104",
        age:'20',
        image:'https://th.bing.com/th/id/OIP.GlXqxcR9EmviN5kuwaUsMQHaIB?rs=1&pid=ImgDetMain',
        Name: "John Doe",
        fname: "John",
        lname: "Doe",
        email: "john.doe@gmail.com",
        phone: "+1(609)784-5678",
        About: "dsl,;fkasfklmerokfv, m ,fmgkmfvn jfdgldfgjlgarunvffjl",
        inProgress: ["1", "2", "3"],
        progress: ["4", "5", "6"],
        Nationality: "EGYPT",
        Country: "EGYPT",
        City: "Cairo",
        University: "international Islamic University",
        Major: "Computer Science",
        GraduationYear: "2020",
        password: "12345678",
        Role: "Admin",
        Status: "Active",
        Score: 0,
      },
      {
        ID: "dl-2851",
        age:'20',
        image:'https://th.bing.com/th/id/OIP.GlXqxcR9EmviN5kuwaUsMQHaIB?rs=1&pid=ImgDetMain',
        Name: "John Doe",
        fname: "John",
        lname: "Doe",
        email: "john.doe@gmail.com",
        phone: "+1(609)784-5678",
        About: "dsl,;fkasfklmerokfv, m ,fmgkmfvn jfdgldfgjlgarunvffjl",
        inProgress: ["1", "2", "3"],
        progress: ["4", "5", "6"],
        Nationality: "EGYPT",
        Country: "EGYPT",
        City: "Cairo",
        University: "international Islamic University",
        Major: "Computer Science",
        GraduationYear: "2020",
        password: "12345678",
        Role: "Admin",
        Status: "Active",
        Score: 0,
      },
      {
        ID: "dl-41281",
        age:'20',
        image:'https://th.bing.com/th/id/OIP.GlXqxcR9EmviN5kuwaUsMQHaIB?rs=1&pid=ImgDetMain',
        Name: "John Doe",
        fname: "John",
        lname: "Doe",
        email: "john.doe@gmail.com",
        phone: "+1(609)784-5678",
        About: "dsl,;fkasfklmerokfv, m ,fmgkmfvn jfdgldfgjlgarunvffjl",
        inProgress: ["1", "2", "3"],
        progress: ["4", "5", "6"],
        Nationality: "EGYPT",
        Country: "EGYPT",
        City: "Cairo",
        University: "international Islamic University",
        Major: "Computer Science",
        GraduationYear: "2020",
        password: "12345678",
        Role: "Admin",
        Status: "Active",
        Score: 0,
      },
      {
        ID: "dl-6814",
        age:'20',
        image:'https://th.bing.com/th/id/OIP.GlXqxcR9EmviN5kuwaUsMQHaIB?rs=1&pid=ImgDetMain',
        Name: "xx Doe",
        fname: "xx",
        lname: "Doe",
        email: "john.doe@gmail.com",
        phone: "+1(609)784-5678",
        About: "dsl,;fkasfklmerokfv, m ,fmgkmfvn jfdgldfgjlgarunvffjl",
        inProgress: ["1", "2", "3"],
        progress: ["4", "5", "6"],
        Nationality: "EGYPT",
        Country: "EGYPT",
        City: "Cairo",
        University: "international Islamic University",
        Major: "Computer Science",
        GraduationYear: "2020",
        password: "12345678",
        Role: "Student",
        EarnedCertificates: [
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            DateDay: "5th",
            DateMonth: "Jun",
            certificate:
              "https://images.pexels.com/photos/268533/pexels-photo-268533.jpeg?cs=srgb&dl=pexels-pixabay-268533.jpg&fm=jpg",
              image:'https://th.bing.com/th/id/OIP.GlXqxcR9EmviN5kuwaUsMQHaIB?rs=1&pid=ImgDetMain',
          },
        ],
        Status: "Inactive",
        Score: 0,
        upcomingExams: [
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            DateDay: "5th",
            DateMonth: "Jun",
            date: "12:30",
            category: "web",
            level: "1",
          },
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            DateDay: "5th",
            DateMonth: "Jun",
            date: "12:30",
            category: "web",
            level: "1",
          },
        ],
        RegisteredCourses: ["1", "2", "7"],
      },
      {
        ID: "dl-51512",
        age:'20',
        image:'https://th.bing.com/th/id/OIP.GlXqxcR9EmviN5kuwaUsMQHaIB?rs=1&pid=ImgDetMain',
        Name: "yyy Doe",
        fname: "yyy",
        lname: "Doe",
        email: "john.doe@gmail.com",
        phone: "+1(609)784-5678",
        About: "dsl,;fkasfklmerokfv, m ,fmgkmfvn jfdgldfgjlgarunvffjl",
        inProgress: ["1", "2", "3"],
        progress: ["4", "5", "6"],
        Nationality: "EGYPT",
        Country: "EGYPT",
        City: "Cairo",
        University: "international Islamic University",
        Major: "Computer Science",
        GraduationYear: "2020",
        password: "12345678",
        Role: "Instructor",
        Status: "Active",
        Score: 0,
        upcomingExams: [
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            DateDay: "5th",
            DateMonth: "Jun",
            date: "12:30",
            category: "web",
            level: "1",
          },
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            DateDay: "5th",
            DateMonth: "Jun",
            date: "12:30",
            category: "web",
            level: "1",
          },
        ],
        onGoingCourses: ["1", "2", "3"],
      },
      {
        ID: "dl-51014",
        age:'20',
        image:'https://th.bing.com/th/id/OIP.GlXqxcR9EmviN5kuwaUsMQHaIB?rs=1&pid=ImgDetMain',
        Name: "xx Doe",
        fname: "xx",
        lname: "Doe",
        email: "john.doe@gmail.com",
        phone: "+1(609)784-5678",
        About: "dsl,;fkasfklmerokfv, m ,fmgkmfvn jfdgldfgjlgarunvffjl",
        inProgress: [
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            level: "1",
          },
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            level: "1",
          },
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            level: "1",
          },
        ],
        progress: [
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            level: "1",
          },
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            level: "1",
          },
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            level: "1",
          },
        ],
        Nationality: "EGYPT",
        Country: "EGYPT",
        City: "Cairo",
        University: "international Islamic University",
        Major: "Computer Science",
        GraduationYear: "2020",
        password: "12345678",
        Role: "Student",
        EarnedCertificates: [
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            DateDay: "5th",
            DateMonth: "Jun",
            certificate:
              "https://images.pexels.com/photos/268533/pexels-photo-268533.jpeg?cs=srgb&dl=pexels-pixabay-268533.jpg&fm=jpg",
              image:'https://th.bing.com/th/id/OIP.GlXqxcR9EmviN5kuwaUsMQHaIB?rs=1&pid=ImgDetMain',
          },
        ],
        Status: "Active",
        Score: 0,
        upcomingExams: [
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            DateDay: "5th",
            DateMonth: "Jun",
            date: "12:30",
            category: "web",
            level: "1",
          },
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            DateDay: "5th",
            DateMonth: "Jun",
            date: "12:30",
            category: "web",
            level: "1",
          },
        ],
        RegisteredCourses: ["1", "2", "7"],
      },
      {
        ID: "dl-48615",
        age:'20',
        image:'https://th.bing.com/th/id/OIP.GlXqxcR9EmviN5kuwaUsMQHaIB?rs=1&pid=ImgDetMain',
        Name: "yyy Doe",
        fname: "yyy",
        lname: "Doe",
        email: "john.doe@gmail.com",
        phone: "+1(609)784-5678",
        About: "dsl,;fkasfklmerokfv, m ,fmgkmfvn jfdgldfgjlgarunvffjl",
        inProgress: ["1", "2", "3"],
        progress: ["4", "5", "6"],
        Nationality: "EGYPT",
        Country: "EGYPT",
        City: "Cairo",
        University: "international Islamic University",
        Major: "Computer Science",
        GraduationYear: "2020",
        password: "12345678",
        Role: "Instructor",
        Status: "Inactive",
        Score: 0,
        upcomingExams: [
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            DateDay: "5th",
            DateMonth: "Jun",
            date: "12:30",
            category: "web",
            level: "1",
          },
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            DateDay: "5th",
            DateMonth: "Jun",
            date: "12:30",
            category: "web",
            level: "1",
          },
        ],
        onGoingCourses: ["1", "2", "3"],
      },
      {
        ID: "dl-56814",
        age:'20',
        image:'https://th.bing.com/th/id/OIP.GlXqxcR9EmviN5kuwaUsMQHaIB?rs=1&pid=ImgDetMain',
        Name: "xx Doe",
        fname: "xx",
        lname: "Doe",
        email: "john.doe@gmail.com",
        phone: "+1(609)784-5678",
        About: "dsl,;fkasfklmerokfv, m ,fmgkmfvn jfdgldfgjlgarunvffjl",
        inProgress: [
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            level: "1",
          },
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            level: "1",
          },
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            level: "1",
          },
        ],
        progress: [
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            level: "1",
          },
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            level: "1",
          },
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            level: "1",
          },
        ],
        Nationality: "EGYPT",
        Country: "EGYPT",
        City: "Cairo",
        University: "international Islamic University",
        Major: "Computer Science",
        GraduationYear: "2020",
        password: "12345678",
        Role: "Student",
        EarnedCertificates: [
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            DateDay: "5th",
            DateMonth: "Jun",
            certificate:
              "https://images.pexels.com/photos/268533/pexels-photo-268533.jpeg?cs=srgb&dl=pexels-pixabay-268533.jpg&fm=jpg",
              image:'https://th.bing.com/th/id/OIP.GlXqxcR9EmviN5kuwaUsMQHaIB?rs=1&pid=ImgDetMain',
          },
        ],
        Status: "Inactive",
        Score: 0,
        upcomingExams: [
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            DateDay: "5th",
            DateMonth: "Jun",
            date: "12:30",
            category: "web",
            level: "1",
          },
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            DateDay: "5th",
            DateMonth: "Jun",
            date: "12:30",
            category: "web",
            level: "1",
          },
        ],
        RegisteredCourses: ["1", "2", "7"],
      },
      {
        ID: "dl-5545",
        age:'20',
        image:'https://th.bing.com/th/id/OIP.GlXqxcR9EmviN5kuwaUsMQHaIB?rs=1&pid=ImgDetMain',
        Name: "yyy Doe",
        fname: "yyy",
        lname: "Doe",
        email: "john.doe@gmail.com",
        phone: "+1(609)784-5678",
        About: "dsl,;fkasfklmerokfv, m ,fmgkmfvn jfdgldfgjlgarunvffjl",
        inProgress: ["1", "2", "3"],
        progress: ["4", "5", "6"],
        Nationality: "EGYPT",
        Country: "EGYPT",
        City: "Cairo",
        University: "international Islamic University",
        Major: "Computer Science",
        GraduationYear: "2020",
        password: "12345678",
        Role: "Instructor",
        Status: "Inactive",
        Score: 0,
        upcomingExams: [
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            DateDay: "5th",
            DateMonth: "Jun",
            date: "12:30",
            category: "web",
            level: "1",
          },
          {
            title: "introduction to React JS",
            instructor: " Mohamed Ahmed",
            DateDay: "5th",
            DateMonth: "Jun",
            date: "12:30",
            category: "web",
            level: "1",
          },
        ],
        onGoingCourses: ["1", "2", "3"],
      },
    ],
    header: ["Name", "Status", "ID", "Role", "Edit"],
    user:       {
      
    },
    online: false,
  },
  reducers: {
    SortUsers: (state) => {
      const actionUser = state.Users.filter((user) => user.Status === "Active");
      const InActionUser = state.Users.filter(
        (user) => user.Status !== "Active"
      );
      state.Users = [...actionUser, ...InActionUser];
    },
    upDataActive: (state, action) => {
      let Users = state.Users.filter((user) => user.ID !== action.payload.ID);
      Users = [...Users, action.payload];
      state.Users = Users;
    },
    delUser: (state, action) => {
      console.log(action);
      const Users = state.Users.filter((user) => user.ID != action.payload);
      state.Users = Users;
    },
    upDataUser: (state, action) => {
      let Users = state.Users.filter(
        (user) => user.ID !== action.payload.oldId
      );
      delete action.payload.oldId;
      Users = [...Users, action.payload];
      state.Users = Users;
    },
    LoginUser: (state, action) => {
      state.online = true;
      state.user = action.payload;
    },
    AddUser: (state, action) => {
    const Users = [...state.Users, { ...action.payload }];
    state.Users = Users;
    console.log(state.Users);
    },
    EditProfiles:(state,action)=>{
      var  Users = state.Users.filter(user=> user.ID != state.user.ID)
      state.user= {...state.user, ...action.payload}
      Users =[...Users,state.user]
      state.Users= Users
    },
    Logout: (state) => {
      state.online = false;
    },
    AddCertificate:(state,action)=>{
      const user=  state.Users.find(user=> user.ID== action.payload.userId)
      const course = JSON.parse(action.payload.course)  
      const date= new Date(action.payload.dateAcquired)
    }
  },
});

export const {
  SortUsers,
  upDataActive,
  delUser,
  upDataUser,
  LoginUser,
  AddUser,
  Logout,
  EditProfiles ,
  AddCertificate,
} = Users.actions;

export default Users.reducer;
